[package]
name = "actix-broker"
version = "1.0.0"
authors = ["chris ricketts <chris.ricketts@steribar.com>"]
description = "Message broker for the Actix actor framework"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Chris-Ricketts/actix-broker"
readme = "README.md"
keywords = ["actix", "message", "broker"]
exclude = [".gitignore"]
edition = "2018"

[dependencies]
actix = "0.9.0"
fnv = "1.0"
log = "0.4"

[dev-dependencies]
actix-web = "2.0.0"
